{
  "comments": [
    {
      "key": {
        "uuid": "aa7e2145_9b7ee2f3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 35,
      "author": {
        "id": 1011123
      },
      "writtenOn": "2020-04-01T09:05:33Z",
      "side": 1,
      "message": "Is this still the case after fixing the tests in the followup commit?",
      "range": {
        "startLine": 30,
        "startChar": 0,
        "endLine": 35,
        "endChar": 0
      },
      "revId": "4a2109d0e0a174e86569583d8a0fc8e05215bf4d",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": true
    }
  ]
}